//  Copyright (c) 2014 Hartmut Kaiser
//
//  Distributed under the Boost Software License, Version 1.0. (See accompanying
//  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

#include <hpx/hpx.hpp>

#include <hpxpi/xpi.h>
#include <hpxpi/impl/addr.hpp>
#include <hpxpi/impl/parcel.hpp>

///////////////////////////////////////////////////////////////////////////////
namespace hpxpi
{
    ///////////////////////////////////////////////////////////////////////////
    void register_agas_actions()
    {
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_U8_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_U16_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_U32_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_U64_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_S8_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_S16_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_S32_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_S64_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_F_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_D_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_ADDR_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_ADDRDIFF_ACTION);

        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_U8_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_U16_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_U32_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_U64_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_S8_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_S16_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_S32_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_S64_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_F_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_D_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_ADDR_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_ADDRDIFF_ACTION);

#ifdef HPXPI_HAVE_NATIVE_INT128
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_U128_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_STORE_S128_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_U128_ACTION);
        HPXPI_REGISTER_DIRECT_ACTION(XPI_AGAS_LOAD_S128_ACTION);
#endif
    }
}

